[devDisk]
        path = /devDisk/
        valid users = root
        read only = no
        writable = yes
        browseable = no
        force create mode = 775
        force directory mode = 775
        force user = root
        force group = root

[userDisk]
        path = /userDisk/
        valid users = root
        read only = no
        writable = yes
        browseable = no
        force create mode = 775
        force directory mode = 775
        force user = root
        force group = root

[users]
        path = /userDisk/USERS/
        valid users = root, greetbuzz
        read only = no
        writable = yes
        browseable = yes
        force create mode = 775
        force directory mode = 775
        force user = root
        force group = root