services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
      - '81:81/tcp'

    network_mode: 'host'

    environment:
      TZ: "Asia/Kolkata"

    volumes:
      - /opt/nginx-proxy/data:/data
      - /opt/nginx-proxy/letsencrypt:/etc/letsencrypt

    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s

# docker compose -p essentials -f compose.nginx-proxy.pro.yml up -d --build