---
services:
  codex:
    container_name: codex
    hostname: codex
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - /devDisk:/workspace
      - /opt/codex:/opt/.codex

    working_dir: /workspace

    environment:
      - CODEX_HOME=/opt/.codex
    
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined

    cap_add:
      - SYS_ADMIN
      
    stdin_open: true
    tty: true
    command: sleep infinity
    restart: unless-stopped

    networks:
      devNetwork:
        ipv4_address: 172.20.0.20

networks:
  devNetwork:
    external: true

# docker compose -p ai-tool -f compose.codex.yml up -d --build  