---
services:
  codex:
    container_name: codex
    hostname: codex
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - /devDisk:/workspace
      - /opt/codex:/opt/.codex

    working_dir: /workspace

    environment:
      - CODEX_HOME=/opt/.codex
      - TZ=Asia/Kolkata

    stdin_open: true
    tty: true
    command: sleep infinity
    restart: unless-stopped

    networks:
      devNetwork:
        ipv4_address: 172.20.0.20

    dns:
      - 172.20.0.3

networks:
  devNetwork:
    external: true

# docker compose -p ai-tool -f compose.codex.yml up -d --build  
