services:
  technitium-dns:
    image: technitium/dns-server:latest
    container_name: technitium-dns
    hostname: dns-server
    
    restart: unless-stopped

    ports:
      - 5380:5380/tcp

    environment:
      - DNS_SERVER_DOMAIN=dns.local
      - DNS_SERVER_ADMIN_PASSWORD=9426460841149

    volumes:
      - /opt/technitium/:/etc/dns
    
    networks:
      devNetwork:
        ipv4_address: 172.20.0.3

networks:
  devNetwork:
    external: true

# docker compose -p essential -f compose.technitium.yml up -d --build  
