services:
  postgres:
    image: postgres:18
    container_name: postgres-db
    restart: always

    volumes:
      - /opt/postgresql:/var/lib/postgresql

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Greet@8866

    networks:
      devNetwork:
        ipv4_address: 172.20.0.6

networks:
  devNetwork:
    external: true

# docker compose -p essential -f compose.postgreSQL.yml up -d --build  