services:
  pgAdmin:
    image: dpage/pgadmin4:latest
    hostname: pgAdmin4
    container_name: pgAdmin4
    restart: unless-stopped
    volumes:
      - /opt/pgadmin:/var/lib/pgadmin

    networks:
      lan_net:
        ipv4_address: 192.168.200.11

    environment:
      PGADMIN_DEFAULT_EMAIL: developers@greet.codes
      PGADMIN_DEFAULT_PASSWORD: Greet@8866
      PGADMIN_LISTEN_PORT: 5050

networks:
  lan_net:
    external: true

# docker compose -p essential -f compose.pgAdmin.yml up -d --build  
# sudo chown -R 5050:5050 /opt/pgadmin