services:
  samba:
    image: dockurr/samba:latest
    container_name: samba
    restart: always

    environment:
      - NAME=devDisk
      - USER=root
      - PASS=9426460841149
      - UID=0
      - GID=0

    ports:
      - "445:445/tcp"

    volumes:
      - /devDisk:/storage

    networks:
      devNetwork:
        ipv4_address: 172.20.0.5

networks:
  devNetwork:
    external: true
    
# docker compose -p essential -f compose.samba.yml up -d --build 